version: '3.8'

services:
  web_debug:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --settings=verionlabs_django.settings
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    ports:
      - "8002:8000"
    env_file:
      - .env.debug
    depends_on:
      - db
      
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: website_db
      POSTGRES_USER: website_user
      POSTGRES_PASSWORD: website_password
    ports:
      - "5433:5432"

volumes:
  postgres_data: