version: '3.8'

services:
  web_debug:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --settings=verionlabs_django.settings
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    ports:
      - "8002:8000"
    env_file:
      - .env.debug
    depends_on:
      - db
      - redis
      
  # Celery worker for background tasks
  celery_worker:
    build: .
    command: celery -A verionlabs_django worker --loglevel=info --concurrency=2
    volumes:
      - .:/app
    env_file:
      - .env.debug
    depends_on:
      - db
      - redis
      
  # Celery beat for scheduled tasks
  celery_beat:
    build: .
    command: celery -A verionlabs_django beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    env_file:
      - .env.debug
    depends_on:
      - db
      - redis
      
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: website_db
      POSTGRES_USER: website_user
      POSTGRES_PASSWORD: website_password
    ports:
      - "5433:5432"
      
  # Redis for Celery broker
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"

volumes:
  postgres_data: