services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-available:/etc/nginx/sites-available
      - ./nginx/sites-available:/etc/nginx/sites-enabled
      - ./nginx/ssl-params.conf:/etc/nginx/ssl-params.conf
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
      # For SSL certificates (uncomment in production)
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - web
    restart: unless-stopped

  web:
    build: .
    command: sh -c "gunicorn --bind 0.0.0.0:8000 --workers 2 --threads 4 --worker-class gthread --log-level warning --access-logfile $${GUNICORN_ACCESS_LOGFILE:-/dev/null} --error-logfile $${GUNICORN_ERROR_LOGFILE:--} verionlabs_django.wsgi:application"
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    ports:
      - "8002:8000"
    env_file:
      - .env.production
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: website_production_db
      POSTGRES_USER: website_prod_user
      POSTGRES_PASSWORD: "OhP6*dO69bj0z0:D`Q:{!"
    restart: unless-stopped
    ports:
      - "5434:5432"

volumes:
  postgres_prod_data: