# Generated by Django 4.2.24 on 2025-09-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='VerionLabs', max_length=100)),
                ('domain', models.CharField(default='verionlabs.com', max_length=100)),
                ('email', models.EmailField(default='contact@verionlabs.com', max_length=254)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
