# Generated by Django 4.2.24 on 2025-09-23 05:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('archived', 'Archived')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes for follow-up')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='demos/')),
                ('image_url', models.URLField(blank=True, help_text='External image URL if not uploading', null=True)),
                ('live_demo_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('slug', models.SlugField(help_text='URL slug for this demo', unique=True)),
                ('meta_description', models.TextField(blank=True, help_text='Meta description for SEO')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(help_text='URL path or external URL', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_external', models.BooleanField(default=False, help_text='Is this an external link?')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Brief description for cards')),
                ('detailed_description', models.TextField(help_text='Detailed description for service pages')),
                ('icon', models.CharField(choices=[('cloud', 'Cloud'), ('brain', 'Brain/AI'), ('code', 'Code'), ('database', 'Database'), ('mobile', 'Mobile'), ('security', 'Security'), ('analytics', 'Analytics'), ('integration', 'Integration')], default='code', max_length=20)),
                ('featured', models.BooleanField(default=True, help_text='Show on homepage')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('slug', models.SlugField(help_text='URL slug for this service', unique=True)),
                ('meta_description', models.TextField(blank=True, help_text='Meta description for SEO')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('image_url', models.URLField(blank=True, help_text='External image URL if not uploading', null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('featured', models.BooleanField(default=True, help_text='Show on about page')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_story_title',
            field=models.CharField(default='Our Story', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_vision_content',
            field=models.TextField(default='To be the trusted technology partner that empowers businesses to thrive in the digital future, one innovative solution at a time.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_vision_title',
            field=models.CharField(default='Our Vision', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='address',
            field=models.TextField(default='123 Innovation Drive, Tech Valley, CA 94000'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='contact_cta_button_text',
            field=models.CharField(default='Get Started Today', max_length=50),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='contact_cta_description',
            field=models.TextField(default="Let's discuss how our innovative solutions can help you achieve your goals and stay ahead of the competition."),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='contact_cta_title',
            field=models.CharField(default='Ready to Transform Your Business?', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='description',
            field=models.TextField(default='VerionLabs provides innovative software solutions for modern businesses, specializing in cloud architecture, AI & machine learning, and custom web applications.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='github_url',
            field=models.URLField(blank=True, default='https://github.com/verionlabs', null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_cta_text',
            field=models.CharField(default='Explore Our Services', max_length=50),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_headline',
            field=models.CharField(default='Innovative Software Solutions for Modern Business', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_subheadline',
            field=models.TextField(default='We transform ideas into powerful digital experiences that drive business growth and technological advancement.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='linkedin_url',
            field=models.URLField(blank=True, default='https://linkedin.com/company/verionlabs', null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='meta_keywords',
            field=models.TextField(default='software development, web applications, cloud architecture, AI, machine learning', help_text='Comma-separated keywords'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='mission',
            field=models.TextField(default='We empower businesses with cutting-edge technology solutions that drive growth, efficiency, and innovation in the digital age.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='mission_content',
            field=models.TextField(default='At VerionLabs, we believe technology should be a catalyst for business success. We partner with companies from startups to enterprises, delivering custom software solutions that solve real-world challenges and unlock new opportunities for growth.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='mission_title',
            field=models.CharField(default='Our Mission', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='twitter_url',
            field=models.URLField(blank=True, default='https://twitter.com/verionlabs', null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='StoryParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('site_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_paragraphs', to='website.siteconfig')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='website.service')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('service', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DemoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('demo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='website.demo')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('demo', 'name')},
            },
        ),
    ]
