# Generated by Django 4.2.24 on 2025-09-23 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_contactinquiry_demo_navigationitem_service_and_more'),
    ]

    operations = [
    ]
