# Generated by Django 4.2.24 on 2025-09-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20250923_0556'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Show the development banner on the website')),
                ('message', models.CharField(default='Development in Progress - Opening Soon!', help_text='Banner message text', max_length=200)),
                ('background_color', models.CharField(default='bg-blue-600', help_text='Tailwind CSS background color class', max_length=20)),
                ('text_color', models.CharField(default='text-white', help_text='Tailwind CSS text color class', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Development Banner',
                'verbose_name_plural': 'Development Banner',
            },
        ),
    ]
