# Generated by Django 4.2.24 on 2025-09-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_developmentbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='maintenance_mode',
            field=models.BooleanField(default=False, help_text='Show maintenance page for all users except admin/staff'),
        ),
    ]
