# Generated by Django 4.2.24 on 2025-09-25 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_siteconfig_maintenance_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL slug for this blog post', unique=True)),
                ('excerpt', models.TextField(help_text='Short summary for blog listing (max 300 characters)', max_length=300)),
                ('content', models.TextField(help_text='Full blog post content (supports HTML)')),
                ('author_name', models.CharField(default='VerionLabs Team', max_length=100)),
                ('author_bio', models.TextField(blank=True, help_text='Optional author bio')),
                ('featured_image', models.ImageField(blank=True, help_text='Featured image for the blog post', null=True, upload_to='blog/')),
                ('featured_image_url', models.URLField(blank=True, help_text='External image URL if not uploading', null=True)),
                ('is_published', models.BooleanField(default=False, help_text='Publish this blog post')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_description', models.TextField(blank=True, help_text='Meta description for SEO (recommended 150-160 characters)')),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=200)),
                ('featured', models.BooleanField(default=False, help_text='Feature this post on homepage')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order for featured posts')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL slug for this page', unique=True)),
                ('content', models.TextField(help_text='Page content (supports HTML)')),
                ('meta_description', models.TextField(blank=True, help_text='Meta description for SEO')),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Make this page accessible')),
                ('show_in_footer', models.BooleanField(default=False, help_text='Show link in footer')),
                ('footer_order', models.PositiveIntegerField(default=0, help_text='Display order in footer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Static Page',
                'verbose_name_plural': 'Static Pages',
                'ordering': ['title'],
            },
        ),
    ]
