# Generated by Django 4.2.24 on 2025-09-25 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_blogpost_staticpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticpage',
            name='footer_order',
        ),
        migrations.RemoveField(
            model_name='staticpage',
            name='show_in_footer',
        ),
    ]
