# Generated by Django 4.2.24 on 2025-09-26 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_footer_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(help_text='URL slug for this tag', unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description for this tag')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Blog Tag',
                'verbose_name_plural': 'Blog Tags',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='url',
            field=models.CharField(help_text="URL path (e.g., '/services/') or external URL", max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for categorizing this post', related_name='blog_posts', to='website.blogtag'),
        ),
    ]
