// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/16/2025, 9:10:06 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/mp/Projects/website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mp/Projects/website/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mp/Projects/website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mp/Projects/website/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mp/Projects/website/plugins/**/*.{js,ts,mjs}","/Users/mp/Projects/website/composables/**/*.{js,ts,mjs}","/Users/mp/Projects/website/utils/**/*.{js,ts,mjs}","/Users/mp/Projects/website/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mp/Projects/website/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/mp/Projects/website/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/mp/Projects/website/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;