# Generated by Django 4.2.24 on 2025-09-24 00:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Coupon code (e.g., 'WELCOME20')", max_length=50, unique=True)),
                ('name', models.CharField(help_text='Internal name for the coupon', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the coupon offer')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage (0-100) or fixed amount in USD', max_digits=10)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Maximum number of times this coupon can be used (blank for unlimited)', null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('minimum_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum purchase amount required', max_digits=10, null=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, help_text='Leave blank for no expiration', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Starter', 'Growth', 'Premium'", max_length=100)),
                ('description', models.TextField(help_text='Brief description of the tier')),
                ('max_users', models.PositiveIntegerField(help_text='Maximum number of users allowed (0 for unlimited)')),
                ('monthly_price', models.DecimalField(decimal_places=2, help_text='Monthly subscription price in USD', max_digits=10)),
                ('annual_price', models.DecimalField(blank=True, decimal_places=2, help_text='Annual subscription price in USD (optional)', max_digits=10, null=True)),
                ('features', models.JSONField(default=list, help_text='List of features included in this tier')),
                ('is_popular', models.BooleanField(default=False, help_text='Mark as popular choice (for highlighting in pricing table)')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing Tier',
                'verbose_name_plural': 'Pricing Tiers',
                'ordering': ['sort_order', 'monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Church Directory', max_length=200)),
                ('site_description', models.TextField(default='The Complete Church Directory Solution for Modern Congregations')),
                ('hero_headline', models.CharField(default='Stay Connected with Your Church Family – Instantly & Securely', max_length=200)),
                ('hero_subline', models.TextField(default='Secure member directories that bring congregations closer together')),
                ('support_email', models.EmailField(default='support@verionlabs.com', max_length=254)),
                ('sales_email', models.EmailField(default='sales@verionlabs.com', max_length=254)),
                ('show_pricing', models.BooleanField(default=True)),
                ('show_testimonials', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('app_store_url', models.URLField(blank=True)),
                ('google_play_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Website Configuration',
                'verbose_name_plural': 'Website Configuration',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('church_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coupon_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='church_directory.coupon')),
                ('pricing_tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='church_directory.pricingtier')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('church_name', models.CharField(blank=True, max_length=200)),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField(blank=True)),
                ('source', models.CharField(default='website', help_text="Source of the lead (e.g., 'pricing_page', 'contact_form')", max_length=50)),
                ('is_contacted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interested_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='church_directory.pricingtier')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='applicable_tiers',
            field=models.ManyToManyField(blank=True, help_text='Leave blank to apply to all tiers', to='church_directory.pricingtier'),
        ),
    ]
