# Generated by Django 4.2.24 on 2025-09-24 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('bio', models.TextField(help_text='Brief description of the team member')),
                ('avatar_initials', models.CharField(help_text="2-3 initials for avatar (e.g., 'MP')", max_length=3)),
                ('avatar_color', models.CharField(default='bg-gradient-to-br from-blue-400 to-blue-600', help_text="Tailwind CSS classes for avatar background (e.g., 'bg-gradient-to-br from-blue-400 to-blue-600')", max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Show this team member on the website')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which to display (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
