# Generated by Django 4.2.24 on 2025-09-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_directory', '0002_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteconfig',
            name='help_center_url',
            field=models.URLField(blank=True, help_text='URL for Help Center page (external link)'),
        ),
        migrations.AddField(
            model_name='websiteconfig',
            name='privacy_policy_url',
            field=models.URLField(blank=True, help_text='URL for Privacy Policy page (external link)'),
        ),
        migrations.AddField(
            model_name='websiteconfig',
            name='terms_of_service_url',
            field=models.URLField(blank=True, help_text='URL for Terms of Service page (external link)'),
        ),
    ]
