# Generated by Django 4.2.24 on 2025-09-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_directory', '0004_subscription_backend_integration_error_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutStoryParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Story Paragraph',
                'verbose_name_plural': 'About Story Paragraphs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('users', 'Users'), ('shield', 'Shield'), ('users-group', 'User Group'), ('clipboard', 'Clipboard'), ('mobile', 'Mobile'), ('cog', 'Settings'), ('chart', 'Chart'), ('bell', 'Bell'), ('heart', 'Heart'), ('lock', 'Lock')], default='users', max_length=20)),
                ('featured_on_homepage', models.BooleanField(default=True, help_text='Show on homepage')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_name', models.CharField(help_text="e.g., 'Pastor Mike', 'Sarah'", max_length=100)),
                ('persona_role', models.CharField(help_text="e.g., 'The Ministry Leader', 'The Caring Congregant'", max_length=100)),
                ('quote', models.TextField(help_text='The testimonial quote')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Use Case',
                'verbose_name_plural': 'Use Cases',
                'ordering': ['order', 'persona_name'],
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('heart', 'Heart'), ('shield', 'Shield'), ('check', 'Check'), ('users', 'Users'), ('info', 'Info'), ('star', 'Star'), ('cross', 'Cross'), ('hands', 'Hands')], default='heart', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Value',
                'verbose_name_plural': 'Values',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='websiteconfig',
            name='about_headline',
            field=models.CharField(default='Building Stronger Church Communities', max_length=200),
        ),
        migrations.AddField(
            model_name='websiteconfig',
            name='about_story_title',
            field=models.CharField(default='Our Story', max_length=100),
        ),
        migrations.AddField(
            model_name='websiteconfig',
            name='about_subline',
            field=models.TextField(default="Church Directory was born from a simple belief: technology should bring people together, not drive them apart. We're passionate about helping churches foster genuine relationships and meaningful connections."),
        ),
        migrations.AddField(
            model_name='websiteconfig',
            name='about_values_title',
            field=models.CharField(default='Our Values', max_length=100),
        ),
        migrations.AddField(
            model_name='websiteconfig',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='websiteconfig',
            name='company_name',
            field=models.CharField(default='VerionLabs', max_length=100),
        ),
        migrations.AddField(
            model_name='websiteconfig',
            name='cta_button_primary',
            field=models.CharField(default='Start Free Trial', max_length=50),
        ),
        migrations.AddField(
            model_name='websiteconfig',
            name='cta_button_secondary',
            field=models.CharField(default='Schedule Demo', max_length=50),
        ),
        migrations.AddField(
            model_name='websiteconfig',
            name='cta_headline',
            field=models.CharField(default='Ready to Connect Your Congregation?', max_length=200),
        ),
        migrations.AddField(
            model_name='websiteconfig',
            name='cta_subline',
            field=models.TextField(default='Join thousands of churches already using Church Directory to build stronger communities and streamline member management.'),
        ),
        migrations.AddField(
            model_name='websiteconfig',
            name='domain',
            field=models.CharField(default='directory.verionlabs.com', max_length=100),
        ),
        migrations.AddField(
            model_name='websiteconfig',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='websiteconfig',
            name='features_headline',
            field=models.CharField(default='Built Specifically for Churches', max_length=200),
        ),
        migrations.AddField(
            model_name='websiteconfig',
            name='features_subline',
            field=models.TextField(default='Every feature is designed with the unique needs, values, and privacy concerns of faith communities in mind.'),
        ),
        migrations.AddField(
            model_name='websiteconfig',
            name='hero_cta_primary',
            field=models.CharField(default='Get Started Today', max_length=50),
        ),
        migrations.AddField(
            model_name='websiteconfig',
            name='hero_cta_secondary',
            field=models.CharField(default='Learn More', max_length=50),
        ),
        migrations.AddField(
            model_name='websiteconfig',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='websiteconfig',
            name='meta_keywords',
            field=models.TextField(default='church directory, member management, church software, congregation management', help_text='Comma-separated keywords'),
        ),
        migrations.AddField(
            model_name='websiteconfig',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='websiteconfig',
            name='pricing_headline',
            field=models.CharField(default='Simple, Transparent Pricing', max_length=200),
        ),
        migrations.AddField(
            model_name='websiteconfig',
            name='pricing_subline',
            field=models.TextField(default='Choose the plan that fits your congregation size. All plans include our core features with no hidden fees.'),
        ),
        migrations.AddField(
            model_name='websiteconfig',
            name='show_team',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='websiteconfig',
            name='show_use_cases',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='websiteconfig',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='websiteconfig',
            name='use_cases_headline',
            field=models.CharField(default='See It In Action', max_length=200),
        ),
        migrations.AddField(
            model_name='websiteconfig',
            name='use_cases_subline',
            field=models.TextField(default='Real scenarios from churches using Church Directory to strengthen their communities.'),
        ),
    ]
