# Generated by Django 4.2.24 on 2025-09-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_directory', '0005_aboutstoryparagraph_feature_usecase_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='backend_integration_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_started', max_length=20),
        ),
    ]
