# Generated by Django 4.2.24 on 2025-09-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_directory', '0006_alter_subscription_backend_integration_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=100, unique=True)),
                ('organization_schema', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=150)),
                ('organization_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Mobile Auth Token',
                'verbose_name_plural': 'Mobile Auth Tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
